# -*- coding: utf-8 -*-
"""DateTimeIndex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4ZcgIlahDq6rwSsZQGqPHdq9x-7yblE
"""

import pandas as pd 
df = pd.read_csv("/content/aapl.csv",parse_dates=["Date"],index_col = 'Date')
df.head()

df.index

# Partial Date Index: Select Specific Months 
df["2017-01"]

df['2017-06'].head()

df['2017-06'].Close.mean()

df['2017'].head(2)

# select date range 
df['2017-01-08':'2017-01-13']

#Resample 
df['Close'].resample('M').mean().head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
df['Close'].plot()

df['Close'].resample('M').mean().plot(kind='bar')